### PR TITLE
feat: Unit tests for serialize_v0 file model

### PR DESCRIPTION
**Pull request by laurentsimon**
Part of https://github.com/google/model-transparency/issues/57

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Hmm, `pytest` cannot be found in the runner :(

**Review by mihaimaruseac — APPROVED** [review]

**Comment by laurentsimon** [comment]
oops, I might have clicked the auto-merge and the pre-submit was not marked "required". I'm looking at the pre-submit failure and will send a PR

**Comment by mihaimaruseac** [comment]
I made it as required now.

**Comment by laurentsimon** [comment]
I set the pre-submits as required in settings.

**Review by kevinrojano — COMMENTED** [review]
Hjhfhlppkffyj

**Comment by kevinrojano** [comment]
Ujjfgjolvf

**Comment by kevinrojano** [comment]
Kjgjklffkkk

**Comment by kevinrojano** [comment]
model_signing/install/requirements.test.in

**Comment by kevinrojano** [comment]
Dlxkdnsjfjaknzjdlalxvdsos

**Pull request merged**
